import Playground from '@/components/Playground';
import Head from 'next/head';
import { Inter } from '@next/font/google';
import styles from '@/styles/Home.module.css';

const inter = Inter({ subsets: ['latin'] });
export default function PlaygroundPage() {
  return (
    <>
      <Head>
        <title>Modelina Playground</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className="flex flex-col min-h-screen">
          <div className={styles.center}>
            <h1>Modelina generated code</h1>
          </div>
          <Playground />
        </div>
      </main>
    </>
  );
}