import {
  RUST_DEFAULT_PRESET,
  RustFileGenerator,
  RustPackageFeatures,
  defaultRustRenderCompleteModelOptions
} from '../../';
import path from 'path';
import input from './generic-input.json';

const generator = new RustFileGenerator({
  presets: [RUST_DEFAULT_PRESET]
});

generator.generateToPackage(
  input,
  // eslint-disable-next-line no-undef
  path.resolve(__dirname, './runtime-rust'),
  {
    ...defaultRustRenderCompleteModelOptions,
    supportFiles: true, // generate Cargo.toml and lib.rs
    package: {
      packageName: 'asyncapi-rs-example',
      packageVersion: '1.0.0',
      // set authors, homepage, repository, and license
      authors: ['AsyncAPI Rust Champions'],
      homepage: 'https://www.asyncapi.com/tools/modelina',
      repository: 'https://github.com/asyncapi/modelina',
      license: 'Apache-2.0',
      description: 'Rust models generated by AsyncAPI Modelina',
      // support 2018 editions and up
      edition: '2018',
      // enable serde_json
      packageFeatures: [RustPackageFeatures.json] as RustPackageFeatures[]
    }
  }
);
