import {
  RustFileGenerator,
  RustRenderCompleteModelOptions,
  RUST_COMMON_PRESET,
  defaultRustRenderCompleteModelOptions,
  RustPackageFeatures
} from '../../src/generators';
import * as path from 'path';

const openAPIDocument = {
  openapi: '3.1.0',
  info: {
    version: '0.1',
    title:
      'A basic example of how Modelina generates a new type for each non-object types: integers, floats, booleans, strings and arrays.'
  },
  paths: {
    '/example': {
      get: {
        parameters: [
          {
            in: 'path',
            name: 'integerParam',
            schema: {
              type: 'integer',
              format: 'int64',
              title: 'integerParam'
            },
            required: true,
            description: 'An example of integer parameter'
          },
          {
            in: 'path',
            name: 'floatParam',
            schema: {
              type: 'number',
              title: 'floatParam'
            },
            required: true,
            description: 'An example of float parameter'
          },
          {
            in: 'path',
            name: 'booleanParam',
            schema: {
              type: 'boolean',
              title: 'booleanParam'
            },
            required: true,
            description: 'An example of boolean parameter'
          },
          {
            in: 'path',
            name: 'stringParam',
            schema: {
              type: 'string',
              title: 'stringParam'
            },
            required: true,
            description: 'An example of string parameter'
          }
        ],
        responses: {
          200: {
            content: {
              'application/json': {
                schema: {
                  type: 'boolean',
                  title: 'booleanReturn'
                }
              }
            }
          },
          500: {
            content: {
              'application/json': {
                schema: {
                  type: 'array',
                  title: 'ArrayReturn',
                  items: {
                    type: 'string',
                    title: 'StringReturn'
                  }
                }
              }
            }
          }
        }
      }
    }
  }
};

export async function generate(): Promise<void> {
  // initialize the generator from a preset
  const generator = new RustFileGenerator({
    presets: [
      {
        preset: RUST_COMMON_PRESET
      }
    ]
  });
  // Generated files will be written to output/ directory
  const outDir = path.join(__dirname, 'output');

  // Run the file generator with options
  const models = await generator.generateToPackage(openAPIDocument, outDir, {
    ...defaultRustRenderCompleteModelOptions,
    supportFiles: true, // generate Cargo.toml and lib.rs
    package: {
      packageName: 'newtype-idiom-rs-example',
      packageVersion: '1.0.0',
      // set authors, homepage, repository, and license
      authors: ['AsyncAPI Rust Champions'],
      homepage: 'https://www.asyncapi.com/tools/modelina',
      repository: 'https://github.com/asyncapi/modelina',
      license: 'Apache-2.0',
      description: 'Rust models generated by AsyncAPI Modelina',
      // support 2018 editions and up
      edition: '2018',
      // enable serde_json
      packageFeatures: [RustPackageFeatures.json] as RustPackageFeatures[]
    }
  } as RustRenderCompleteModelOptions);
  for (const model of models) {
    console.log(model.result);
  }
}
if (require.main === module) {
  generate();
}
