name: Runtime Testing TypeScript Models
on: 
  push:
    paths: 
      - 'src/generators/typescript/**'
      - 'test/runtime/runtime-typescript/**'
      - 'test/runtime/**typescript**'
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths: 
      - 'src/generators/typescript/**'
      - 'test/runtime/runtime-typescript/**'
      - 'test/runtime/**typescript**'

jobs:
  test:
    name: Runtime Testing TypeScript Models
    if: "github.event.pull_request.draft == false &&!((github.actor == 'asyncapi-bot' && startsWith(github.event.pull_request.title, 'ci: update global workflows')) || (github.actor == 'asyncapi-bot' && startsWith(github.event.pull_request.title, 'chore(release):')) || (github.actor == 'allcontributors' && startsWith(github.event.pull_request.title, 'docs: add')))"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Check package-lock version
        uses: asyncapi/.github/.github/actions/get-node-version-from-package-lock@master
        id: lockversion
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "${{ steps.lockversion.outputs.version }}"
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - name: Build library
        run: npm install && npm run build:prod
      - name: Generate TypeScript models
        run: npm run generate:runtime:typescript
      - name: Run runtime tests
        run: npm run test:runtime:typescript
      

